---

- hosts: raspi
  roles:
  - firstboot

- hosts: ubuntu
  roles:
  - console

- hosts: zoneminder
  roles:
  - console

- hosts: weewx
  roles:
  - firstboot
  - apt
  - common
  - console
  - nginx
  - weewx

