---

#--------------------------
#
# todo - support RedHat(ish)
#

- name: install weewx optional prerequisites
  apt: package={{ item }} state=present
  with_items:
     - sqlite3
     - ftp
     - rsync
  when: ansible_os_family == "Debian"

- name: install weewx mandatory prerequisites
  apt: package={{ item }} state=present
  with_items:
     - python-configobj
     - python-cheetah
     - python-imaging
     - python-serial
     - python-usb
     - python-dev
     - python-pip
     - sqlite3
  when: ansible_os_family == "Debian"

#------------------------- 
#
# common to all
#
# we install only if a 'install_weewx' variable is set to true
# this is done to speedup reruns
#
# TODO - this probably isn't the best way to do this,
#          what if something underlying actual changed ?
#

- get_url:
      url="http://sourceforge.net/projects/weewx/files/latest/download?source=files"
      dest="/tmp/weewx.tgz"
  when: "{{ install_weewx }}"

- name: make tmpdir to build in
  file: dest=/tmp/weewx state=directory
  when: "{{ install_weewx }}"

# note the options here, create a version-neutral tree we can script around
- name: extract weewx
  command: tar zxvf /tmp/weewx.tgz -C /tmp/weewx --strip-components=1
  when: "{{ install_weewx }}"
 
- name: build weewx
  command: chdir=/tmp/weewx ./setup.py build 
  when: "{{ install_weewx }}"
 
- name: install weewx
  command: chdir=/tmp/weewx ./setup.py install --quiet
  when: "{{ install_weewx }}"

#
# unfortunately weewx.conf is not really in .ini format
# so trying it this way blows up at runtime, but it does provide
# a good example of how to use with_items and multiple items per substitution
#
# - name: edit weewx.conf
#   ini_file: dest=/home/weewx/weewx.conf section="{{item.section}}" option="{{item.option}}" value="{{item.value}}"
#   with_items:
#     - { section: 'Station', option: 'location',    value: 'Federal Way, Washington'      }
#     - { section: 'Station', option: 'latitude',    value: 47.31                          }
#     - { section: 'Station', option: 'longitude',   value: -122.123                       }
#     - { section: 'Station', option: 'altitude',    value: '365, foot'                    }
#     - { section: 'Station', option: 'station_url', value: "http://www.skahan.net/weewx"  }

#--------------------------
#
# todo - support RedHat(ish)
#

- name: install startup file
  command: cp /tmp/weewx/util/init.d/weewx.debian /etc/init.d/weewx
  when:
  - ansible_os_family == "Debian"
  - "{{ install_weewx }}"

#--------------------------
#
# common to all
#
- service: name=weewx state=restarted  enabled=yes
  when: "{{ install_weewx }}"

- name: Remove old weewx bin and config backups
  shell: 'rm -rf {{item}}.*'
  with_items:
   - /home/weewx/bin
   - /home/weewx/weewx.conf
  when: "{{ install_weewx }}"

