---

#--------------------------
#
# todo - support RedHat(ish)
#

- name: install weewx optional prerequisites
  apt: package={{ item }} state=present
  with_items:
     - sqlite3
     - ftp
     - rsync
  when: ansible_os_family == "Debian"

- name: install weewx mandatory prerequisites
  apt: package={{ item }} state=present
  with_items:
     - python-configobj
     - python-cheetah
     - python-imaging
     - python-serial
     - python-usb
     - python-dev
     - python-pip
     - sqlite3
  when: ansible_os_family == "Debian"

#------------------------- 
#
# common to all
#
# todo - do not do this if already done unless a flag is set saying reinstall

- name: check if weewx is installed already
  stat: path=/home/weewx
  register: s

- get_url:
      url="http://sourceforge.net/projects/weewx/files/latest/download?source=files"
      dest="/tmp/weewx.tgz"
  when: not s.stat.exists
 
- name: make tmpdir to build in
  file: dest=/tmp/weewx state=directory
  when: not s.stat.exists

# note the options here, create a version-neutral tree we can script around
- name: extract weewx
  command: tar zxvf /tmp/weewx.tgz -C /tmp/weewx --strip-components=1
  when: not s.stat.exists
 
- name: build weewx
  command: chdir=/tmp/weewx ./setup.py build 
  when: not s.stat.exists
 
- name: install weewx
  command: chdir=/tmp/weewx ./setup.py install --quiet
  when: not s.stat.exists

#--------------------------
#
# todo - support RedHat(ish)
#

- name: install startup file
  command: cp /tmp/weewx/util/init.d/weewx.debian /etc/init.d/weewx
  when:
  - ansible_os_family == "Debian"
  - not s.stat.exists

#--------------------------
#
# common to all
#
- service: name=weewx state=restarted  enabled=yes
  when: not s.stat.exists

- name: Remove old weewx bin and config backups
  shell: 'rm -rf {{item}}.*'
  with_items:
   - /home/weewx/bin
   - /home/weewx/weewx.conf
  when: not s.stat.exists

