---

#--------------------------
#
# todo - make this os-aware
#

- name: install weewx optional prerequisites
  apt: package={{ item }} state=present
  with_items:
     - sqlite3
     - ftp
     - rsync

- name: install weewx mandatory prerequisites
  apt: package={{ item }} state=present
  with_items:
     - python-configobj
     - python-cheetah
     - python-imaging
     - python-serial
     - python-usb
     - python-dev
     - python-pip
     - sqlite3

#------------------------- 
#
# common to all
#

- get_url:
      url="http://sourceforge.net/projects/weewx/files/latest/download?source=files"
      dest="/tmp/weewx.tgz"
 
- name: make tmpdir to build in
  file: dest=/tmp/weewx state=directory
 
# note the options here, create a version-neutral tree we can script around
- name: extract weewx
  command: tar zxvf /tmp/weewx.tgz -C /tmp/weewx --strip-components=1
 
- name: build weewx
  command: chdir=/tmp/weewx ./setup.py build 
 
- name: install weewx
  command: chdir=/tmp/weewx ./setup.py install --quiet

- name: install startup file
  command: cp /tmp/weewx/util/init.d/weewx.debian /etc/init.d/weewx

#------------------------- 
#
# todo - make this os-aware
#

- name: set to start on bootup
  command: update-rc.d weewx defaults 98
 
- file: path=/etc/init.d/weewx mode=0755

#------------------------- 
#
# common to all
#

# hope the init.d file starts late enough for ntp to be up
- name: fire it up
  command: service weewx start

