---
- name: main role task1
  debug: msg="hello main role task1"


- name: debug distro
  debug: msg="Hello Debian-7 distro"
  when:
    ansible_distribution == "Debian" and ansible_distribution_major_version == "7"

- name: touch /tmp/foo
  command: touch /tmp/foo
  notify:
    debug_handler

- name: rm /tmp/foo
  command: rm /tmp/foo
  notify:
    rm_handler

