- name: set up serial console
  replace: 
     dest:    /etc/inittab
     regexp:  "^#T0:23:respawn:/sbin/getty -L ttyS0 9600 vt100$"
     replace: "T0:23:respawn:/sbin/getty -L ttyS0 115200 vt100"
  notify:
     - telinit_q
